// export const DANGCHUANBI = "DANGCHUANBI";
export const CHOXACNHAN = "CHOXACNHAN";
// export const DANGIAO = "DANGIAO";
// export const DANHAN = "DANHAN";
// export const DAGUI = "DAGUI";
// export const DATHANHTOAN = "DATHANHTOAN";
export const THANHCONG = "THANHCONG";
export const DAHUY = "DAHUY";
export const THATBAI = "THATBAI";

export const DELIVERY_STATUS = {
  YES: "YES",
  NO: "NO",
};

export const ORDER_STATUS = {
  ORDER_STATUS_WAITING_ACCEPT: "ORDER_STATUS_WAITING_ACCEPT",
  ORDER_STATUS_ACCEPT: "ORDER_STATUS_ACCEPT",
  ORDER_STATUS_DELIVERY: "ORDER_STATUS_DELIVERY",
  ORDER_STATUS_FINISH_DELIVERY: "ORDER_STATUS_FINISH_DELIVERY",
  ORDER_STATUS_SUCCESS: "ORDER_STATUS_SUCCESS",
  ORDER_STATUS_FAIL: "ORDER_STATUS_FAIL",
  ORDER_STATUS_CUSTOMER_CANCEL: "ORDER_STATUS_CUSTOMER_CANCEL",
  ORDER_STATUS_CUSTOMER_CANCEL_RECEIVE: "ORDER_STATUS_CUSTOMER_CANCEL_RECEIVE",
};
export const ORDER_STATUS_LABEL = {
  ORDER_STATUS_WAITING_ACCEPT: "Chờ xác nhận",
  ORDER_STATUS_ACCEPT: "Đã xác nhận",
  ORDER_STATUS_DELIVERY: "Chờ vận chuyển",
  ORDER_STATUS_FINISH_DELIVERY: "Đang vận chuyển",
  ORDER_STATUS_SUCCESS: "Hoàn thành",
  ORDER_STATUS_FAIL: "Tạo đơn thất bại",
  ORDER_STATUS_CUSTOMER_CANCEL: "Hủy đơn",
  ORDER_STATUS_CUSTOMER_CANCEL_RECEIVE: "Không nhận hàng",
};
export const ORDER_STATUS_ARRAY = [
  ORDER_STATUS.ORDER_STATUS_WAITING_ACCEPT,
  ORDER_STATUS.ORDER_STATUS_ACCEPT,
  ORDER_STATUS.ORDER_STATUS_DELIVERY,
  ORDER_STATUS.ORDER_STATUS_FINISH_DELIVERY,
  ORDER_STATUS.ORDER_STATUS_SUCCESS,
  ORDER_STATUS.ORDER_STATUS_FAIL,
  ORDER_STATUS.ORDER_STATUS_CUSTOMER_CANCEL,
  ORDER_STATUS.ORDER_STATUS_CUSTOMER_CANCEL_RECEIVE,
];
