// export const DANGCHUANBI = "DANGCHUANBI";
export const CHOXACNHAN = "CHOXACNHAN";
// export const DANGIAO = "DANGIAO";
// export const DANHAN = "DANHAN";
// export const DAGUI = "DAGUI";
// export const DATHANHTOAN = "DATHANHTOAN";
export const THANHCONG = "THANHCONG";
export const DAHUY = "DAHUY";
export const THATBAI = "THATBAI";

export const DELIVERY_STATUS = {
  YES: "YES",
  NO: "NO",
};

export const ORDER_STATUS = {
  ORDER_STATUS_WAITING_ACCEPT: "ORDER_STATUS_WAITING_ACCEPT",
  ORDER_STATUS_ACCEPT: "ORDER_STATUS_ACCEPT",
  ORDER_STATUS_DELIVERY: "ORDER_STATUS_DELIVERY",
  ORDER_STATUS_FINISH_DELIVERY: "ORDER_STATUS_FINISH_DELIVERY",
  ORDER_STATUS_SUCCESS: "ORDER_STATUS_SUCCESS",
  ORDER_STATUS_FAIL: "ORDER_STATUS_FAIL",
  ORDER_STATUS_CUSTOMER_CANCEL: "ORDER_STATUS_CUSTOMER_CANCEL",
  ORDER_STATUS_CUSTOMER_CANCEL_RECEIVE: "ORDER_STATUS_CUSTOMER_CANCEL_RECEIVE",
    ORDER_STATUS_SHOP_CANCEL: "ORDER_STATUS_SHOP_CANCEL",
};
export const ORDER_STATUS_OPTIONS = [
  {
    value: ORDER_STATUS.ORDER_STATUS_WAITING_ACCEPT,
    code: 1,
  },
  {
    value: ORDER_STATUS.ORDER_STATUS_ACCEPT,
    code: 2,
  },
  {
    value: ORDER_STATUS.ORDER_STATUS_DELIVERY,
    code: 3,
  },
  {
    value: ORDER_STATUS.ORDER_STATUS_FINISH_DELIVERY,
    code: 4,
  },
  {
    value: ORDER_STATUS.ORDER_STATUS_SUCCESS,
    code: 5,
  },
  {
    value: ORDER_STATUS.ORDER_STATUS_FAIL,
    code: 8,
  },
  {
    value: ORDER_STATUS.ORDER_STATUS_CUSTOMER_CANCEL,
    code: 6,
  },
  {
    value: ORDER_STATUS.ORDER_STATUS_CUSTOMER_CANCEL_RECEIVE,
    code: 7,
  },
   {
    value: ORDER_STATUS.ORDER_STATUS_FAIL, // Label: "Tạo đơn thất bại"
    code: 8,
    // color: "error"
  },
  { // <<<< THÊM OBJECT NÀY VÀO
    value: ORDER_STATUS.ORDER_STATUS_SHOP_CANCEL, // Lấy từ ORDER_STATUS object
    code: 9, // Đây là giá trị số mà BE trả về cho "Shop hủy đơn"
    // color: "error" // Hoặc một màu phù hợp khác
  },
];
export const ORDER_STATUS_LABEL = {
  ORDER_STATUS_WAITING_ACCEPT: "Chờ xác nhận",
  ORDER_STATUS_ACCEPT: "Đã xác nhận",
  ORDER_STATUS_DELIVERY: "Chờ vận chuyển",
  ORDER_STATUS_FINISH_DELIVERY: "Đang vận chuyển",
  ORDER_STATUS_SUCCESS: "Hoàn thành",
  ORDER_STATUS_FAIL: "Tạo đơn thất bại",
  ORDER_STATUS_CUSTOMER_CANCEL: "Hủy đơn",
  ORDER_STATUS_CUSTOMER_CANCEL_RECEIVE: "Giao hàng thất bại",
    ORDER_STATUS_SHOP_CANCEL: "Shop hủy đơn",
};
export const ORDER_STATUS_ARRAY = [
  ORDER_STATUS.ORDER_STATUS_WAITING_ACCEPT,
  ORDER_STATUS.ORDER_STATUS_ACCEPT,
  ORDER_STATUS.ORDER_STATUS_DELIVERY,
  ORDER_STATUS.ORDER_STATUS_FINISH_DELIVERY,
  ORDER_STATUS.ORDER_STATUS_SUCCESS,
  ORDER_STATUS.ORDER_STATUS_FAIL,
  ORDER_STATUS.ORDER_STATUS_CUSTOMER_CANCEL,
  ORDER_STATUS.ORDER_STATUS_CUSTOMER_CANCEL_RECEIVE,
];
